#  Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
"""Env constant"""

AGENT_CACHE_ENABLE_KEY = "AGENT_CACHE_ENABLE"

# 环境中保存的worker_id
ASYNC_WORKER_ID_KEY = "ASYNC_WORKER_ID"

BATCH_SIZE_KEY = "BATCH_SIZE"

CACHE_FILE_PREFIX_KEY = "CACHE_FILE_PREFIX"
CACHE_TTL_SECONDS_KEY = "CACHE_TTL_SECONDS"
MAX_AGENT_CACHE_NUM_KEY = "MAX_AGENT_CACHE_NUM"
MAX_CACHE_DATA_SIZE_KEY = "MAX_CACHE_DATA_SIZE"
MAX_IR_CACHE_NUM_KEY = "MAX_IR_CACHE_NUM"
MAX_WORKFLOW_CACHE_NUM_KEY = "MAX_WORKFLOW_CACHE_NUM"

CELERY_ENABLE_KEY = "CELERY_ENABLE"

CLOSE_URL_JUDGE_SWITCH_KEY = "CLOSE_URL_JUDGE_SWITCH"

CODE_SANDBOX_TIMEOUT_KEY = "CODE_SANDBOX_TIMEOUT"
SECURITY_SANDBOX_CERTIFICATION_PATH_KEY = "SECURITY_SANDBOX_CERTIFICATION_PATH"
SECURITY_SANDBOX_SERVER_KEY = "SECURITY_SANDBOX_SERVER"
SECURITY_SANDBOX_SSL_VERIFY_KEY = "SECURITY_SANDBOX_SSL_VERIFY"

DATASOURCE_GAUSSDB_PASSWORD_KEY = "DATASOURCE_GAUSSDB_PASSWORD"

DATASOURCE_OBS_BUCKET_KEY = "DATASOURCE_OBS_BUCKET"
DATASOURCE_OBS_ENABLE_SSL = "DATASOURCE_OBS_ENABLE_SSL"

DATASOURCE_REDIS_CALLBACKS_KEY = "DATASOURCE_REDIS_CALLBACKS"
DATASOURCE_REDIS_CLUSTER_NODE_KEY = "DATASOURCE_REDIS_CLUSTER_NODE"
DATASOURCE_REDIS_DATABASE_KEY = "DATASOURCE_REDIS_DATABASE"
DATASOURCE_REDIS_HOST_KEY = "DATASOURCE_REDIS_HOST"
DATASOURCE_REDIS_MAX_CONNECTIONS_KEY = "DATASOURCE_REDIS_MAX_CONNECTIONS"
DATASOURCE_REDIS_MODE_KEY = "DATASOURCE_REDIS_MODE"
DATASOURCE_REDIS_PASSWORD_KEY = "DATASOURCE_REDIS_PASSWORD"
DATASOURCE_REDIS_PORT_KEY = "DATASOURCE_REDIS_PORT"
DATASOURCE_REDIS_PREFIX_KEY = "DATASOURCE_REDIS_PREFIX"
DATASOURCE_REDIS_SOCKET_CONNECT_TIMEOUT_KEY = "DATASOURCE_REDIS_SOCKET_CONNECT_TIMEOUT"
DATASOURCE_REDIS_SOCKET_TIMEOUT_KEY = "DATASOURCE_REDIS_SOCKET_TIMEOUT"
DATASOURCE_REDIS_SSL_CA_CERTS_KEY = "DATASOURCE_REDIS_SSL_CA_CERTS"
DATASOURCE_REDIS_SSL_CERTFILE_KEY = "DATASOURCE_REDIS_SSL_CERTFILE"
DATASOURCE_REDIS_SSL_KEYFILE_KEY = "DATASOURCE_REDIS_SSL_KEYFILE"
DATASOURCE_REDIS_SSL_MODE_KEY = "DATASOURCE_REDIS_SSL_MODE"
DATASOURCE_REDIS_SSL_PASSWD_KEY = "DATASOURCE_REDIS_SSL_PASSWD"
DATASOURCE_REDIS_TTL_KEY = "DATASOURCE_REDIS_TTL"

DATASOURCE_ES_HOST_KEY = "DATASOURCE_ES_HOST"
DATASOURCE_ES_SSL_MODE_KEY = "DATASOURCE_ES_SSL_MODE"
DATASOURCE_ES_PASSWORD_KEY = "DATASOURCE_ES_PASSWORD"
DATASOURCE_ES_USERNAME_KEY = "DATASOURCE_ES_USERNAME"
DATASOURCE_ES_PORT_KEY = "DATASOURCE_ES_PORT"
DATASOURCE_ES_TIMEOUT_KEY = "DATASOURCE_ES_TIMEOUT"
DATASOURCE_ES_API_KEY = "DATASOURCE_ES_API_KEY"

EMBEDDING_BASE_URL_KEY = "EMBEDDING_BASE_URL"
EMBEDDING_API_KEY = "EMBEDDING_API_KEY"

DEFAULT_MODELS_KEY = "DEFAULT_MODELS"

ENABLE_REFINER_KEY = "ENABLE_REFINER"

EXECUTION_CELERY_CONCURRENCY_KEY = "EXECUTION_CELERY_CONCURRENCY"
EXECUTION_CELERY_POOL_KEY = "EXECUTION_CELERY_POOL"
EXECUTION_CRYPTOR_CLASS_KEY = "EXECUTION_CRYPTOR_CLASS"
EXECUTION_CRYPTOR_MODULE_KEY = "EXECUTION_CRYPTOR_MODULE"
EXECUTION_NODE_TIMEOUT_KEY = "EXECUTION_NODE_TIMEOUT"
EXECUTION_STATE_STORAGE_MEDIUM_KEY = "EXECUTION_STATE_STORAGE_MEDIUM"
EXECUTION_SUPPORTED_IR_VERSIONS_KEY = "EXECUTION_SUPPORTED_IR_VERSIONS"

GC_THRESHOLD_PART1_KEY = "GC_THRESHOLD_PART1"
GC_THRESHOLD_PART2_KEY = "GC_THRESHOLD_PART2"
GC_THRESHOLD_PART3_KEY = "GC_THRESHOLD_PART3"

IF_EVAL_KEY = "IF_EVAL"

INSIGHT_SUPPORT_ENCRYPT_KEY = "INSIGHT_SUPPORT_ENCRYPT"
WORKFLOW_HANDLER_ENABLE_INSIGHT_KEY = "WORKFLOW_HANDLER_ENABLE_INSIGHT"

IR_CACHE_ENABLE_KEY = "IR_CACHE_ENABLE"

RULE_CACHE_ENABLE_KEY = "RULE_CACHE_ENABLE"

JIUWEN_CONFIG_PATH_KEY = "JIUWEN_CONFIG_PATH"
JIUWEN_DEFAULT_LANGUAGE_TYPE_KEY = "JIUWEN_DEFAULT_LANGUAGE_TYPE"
JIUWEN_EXTENSION_PATH_KEY = "JIUWEN_EXTENSION_PATH"
JIUWEN_GRAY_DEBUG_KEY = "JIUWEN_GRAY_DEBUG"
JIUWEN_LOG_BACKUP_COUNT_KEY = "JIUWEN_LOG_BACKUP_COUNT"
JIUWEN_LOG_LEVEL_KEY = "JIUWEN_LOG_LEVEL"
JIUWEN_LOG_MAX_BYTES_KEY = "JIUWEN_LOG_MAX_BYTES"
JIUWEN_LOG_PATH_KEY = "JIUWEN_LOG_PATH"

MODEL_CFG_SSL_CERT_PATH_KEY = "MODEL_CFG_SSL_CERT_PATH"
MODEL_CFG_SSL_MODE_KEY = "MODEL_CFG_SSL_MODE"
MODEL_DIR_KEY = "MODEL_DIR"

PLUGIN_CACHE_SIZE_KEY = "PLUGIN_CACHE_SIZE"
PLUGIN_RECALL_APP_CODE_KEY = "PLUGIN_RECALL_APP_CODE"
PLUGIN_RECALL_EMB_CLASS_KEY = "PLUGIN_RECALL_EMB_CLASS"
PLUGIN_RECALL_EMB_DIM_KEY = "PLUGIN_RECALL_EMB_DIM"
PLUGIN_RECALL_EMB_SERVICE_URL_KEY = "PLUGIN_RECALL_EMB_SERVICE_URL"
PLUGIN_RECALL_INFER_FIELDS_KEY = "PLUGIN_RECALL_INFER_FIELDS"
PLUGIN_REQUEST_TIMEOUT_KEY = "PLUGIN_REQUEST_TIMEOUT"
PLUGIN_SKIP_SSRF_CHECK_KEY = "PLUGIN_SKIP_SSRF_CHECK"
PLUGIN_SSL_API_CERT_KEY = "PLUGIN_SSL_API_CERT"
PLUGIN_SSL_EMB_CERT_KEY = "PLUGIN_SSL_EMB_CERT"
PLUGIN_STORE_KEY = "PLUGIN_STORE"
PLUGIN_WHITE_URLS_KEY = "PLUGIN_WHITE_URLS"
STREAM_PLUGIN_BUFSIZE_KEY = "STREAM_PLUGIN_BUFSIZE"
JIUWEN_PROXY_ENABLE_KEY = "JIUWEN_PROXY_ENABLE"

PROFILE_PATH_KEY = "PROFILE_PATH"

PROMPT_DEFAULT_TEMPLATES_PATH_KEY = "PROMPT_DEFAULT_TEMPLATES_PATH"
PROMPT_MODEL_TYPE_KEY = "PROMPT_MODEL_TYPE"

RAILS_CUSTOM_RAILS_PATH_KEY = "RAILS_CUSTOM_RAILS_PATH"

REDIS_BJ_HOST_KEY = "REDIS_BJ_HOST"
REDIS_CI_HOST_KEY = "REDIS_CI_HOST"
REDIS_DEFAULT_HOST_KEY = "REDIS_DEFAULT_HOST"
REDIS_GY_HOST_KEY = "REDIS_GY_HOST"

RUNTIME_POD_IP_KEY = "RUNTIME_POD_IP"

STREAM_FRAME_TIMEOUT_KEY = "STREAM_FRAME_TIMEOUT"

TLS_CERT_KEY_PASSWD_KEY = "TLS_CERT_KEY_PASSWD"
TLS_CERT_KEY_PATH_KEY = "TLS_CERT_KEY_PATH"
TLS_CERT_PATH_KEY = "TLS_CERT_PATH"

TOOL_SELECTOR_CSB_TOKEN_KEY = "TOOL_SELECTOR_CSB_TOKEN"
TOOL_SELECTOR_TIMEOUT_KEY = "TOOL_SELECTOR_TIMEOUT"
TOOL_SELECTOR_URL_KEY = "TOOL_SELECTOR_URL"

USE_EI_INTENT_KEY = "USE_EI_INTENT"

WORKFLOW_MAX_PARALLEL_COMPONENT_NUM_KEY = "WORKFLOW_MAX_PARALLEL_COMPONENT_NUM"
CONDITION_EXPRESSION_MAX_LEN_KEY = "CONDITION_EXPRESSION_MAX_LEN"
URL_MAX_LEN_KEY = "URL_MAX_LEN"

WORKFLOW_TASK_CANCEL_TIMEOUT_KEY = "WORKFLOW_TASK_CANCEL_TIMEOUT"

MULTI_LAYER_INTENT_DETECTION_PROMPT_KEY = "MULTI_LAYER_INTENT_DETECTION_PROMPT"
