apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-elb
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/elb.class: {{ .Values.service.elb.class }}
    kubernetes.io/elb.health-check-flag: "{{ .Values.service.elb.healthCheckFlag }}"
    kubernetes.io/elb.lb-algorithm: {{ .Values.service.elb.algorithm }}
    kubernetes.io/elb.protocol-port: "{{ .Values.service.elb.protocol }}:{{ .Values.service.port }}"
    kubernetes.io/elb.id: {{ .Values.service.elb.id }}

spec:
  type: {{ .Values.service.type }}
  allocateLoadBalancerNodePorts: true

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

  selector:
    app: {{ include "frontend.name" . }}
