"""refactor_agent_model config

Revision ID: 69cb68688942
Revises: 031b34b4dd30
Create Date: 2026-01-31 16:52:49.151030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '69cb68688942'
down_revision: Union[str, Sequence[str], None] = '031b34b4dd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agent_model_config', sa.JSON(), nullable=True))
        batch_op.drop_column('model')

    with op.batch_alter_table('agent_publish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agent_model_config', sa.JSON(), nullable=True))
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_publish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sqlite.JSON(), nullable=True))
        batch_op.drop_column('agent_model_config')
        batch_op.drop_column('model_id')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sqlite.JSON(), nullable=True))
        batch_op.drop_column('agent_model_config')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
