# Stage 1: Builder environment
FROM node:18-alpine AS builder

WORKDIR /app
COPY frontend .
RUN npm install && npm run build


# Stage 2: Final image - Only copy necessary files from builder stage
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/nginx.conf
COPY docker/privateKeyTool.sh /usr/local/bin/privateKeyTool
RUN chmod +x /usr/local/bin/privateKeyTool
RUN chown root:root /usr/local/bin/privateKeyTool
COPY docker/start_nginx.sh /usr/local/bin/start-nginx.sh
RUN chmod +x /usr/local/bin/start-nginx.sh

EXPOSE 3001

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -f -k https://localhost:3001/ || exit 1

ENTRYPOINT ["/usr/local/bin/start-nginx.sh"]