#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
"""schema updates for develop-20260116

Revision ID: 8d437e686ce9
Revises: 54351e123cf0
Create Date: 2026-01-20 21:07:52.261219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d437e686ce9"
down_revision: Union[str, Sequence[str], None] = "54351e123cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin", sa.Column("desc_mk", sa.Text(), nullable=True))
    op.add_column("plugin", sa.Column("inputs", sa.JSON(), nullable=True))
    op.add_column("plugin_publish", sa.Column("desc_mk", sa.Text(), nullable=True))
    op.add_column("plugin_publish", sa.Column("inputs", sa.JSON(), nullable=True))
    op.add_column(
        "tool",
        sa.Column(
            "available", sa.Boolean(), nullable=False, server_default=sa.text("1")
        ),
    )
    op.alter_column("tool", "available", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool", "available")
    op.drop_column("plugin_publish", "inputs")
    op.drop_column("plugin_publish", "desc_mk")
    op.drop_column("plugin", "inputs")
    op.drop_column("plugin", "desc_mk")
    # ### end Alembic commands ###
