#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
"""auto migration for workflow schema changes

Revision ID: cb2c7a9ff46c
Revises: 8d437e686ce9
Create Date: 2026-01-21 19:24:27.617496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "cb2c7a9ff46c"
down_revision: Union[str, Sequence[str], None] = "8d437e686ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "session_key",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.add_column(
        "workflow", sa.Column("object_key", sa.String(length=512), nullable=True)
    )
    op.alter_column(
        "workflow",
        "schema",
        existing_type=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    op.add_column(
        "workflow_publish",
        sa.Column("object_key", sa.String(length=512), nullable=True),
    )
    op.alter_column(
        "workflow_publish",
        "schema",
        existing_type=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_publish",
        "schema",
        existing_type=mysql.LONGTEXT(),
        type_=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        existing_nullable=True,
    )
    op.drop_column("workflow_publish", "object_key")
    op.alter_column(
        "workflow",
        "schema",
        existing_type=mysql.LONGTEXT(),
        type_=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        existing_nullable=True,
    )
    op.drop_column("workflow", "object_key")
    op.alter_column(
        "user",
        "session_key",
        existing_type=sa.String(length=512),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
