"""agent model

Revision ID: 9fa66e01df94
Revises: 06a1f79bce8b
Create Date: 2026-01-31 14:44:59.028934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fa66e01df94'
down_revision: Union[str, Sequence[str], None] = '06a1f79bce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('agent', sa.Column('agent_model_config', sa.JSON(), nullable=True))
    op.drop_column('agent', 'model')
    op.drop_column('agent_publish', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_publish', sa.Column('model', mysql.JSON(), nullable=True))
    op.add_column('agent', sa.Column('model', mysql.JSON(), nullable=True))
    op.drop_column('agent', 'agent_model_config')
    op.drop_column('agent', 'model_id')
    # ### end Alembic commands ###
