#!/usr/bin/env python3
"""Generate bilingual error-code reference documents from the Manifest."""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path
from typing import Any


OBSERVABILITY_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = OBSERVABILITY_DIR.parents[1]
MANIFEST_PATH = OBSERVABILITY_DIR / "error-codes.yaml"
OUTPUTS = {
    "zh_cn": REPO_ROOT / "docs/zh/reference/error-codes.md",
    "en_us": REPO_ROOT / "docs/en/reference/error-codes.md",
}


TEXT = {
    "zh_cn": {
        "title": "# Studio 2.0 错误码目录",
        "status": "Studio 2.0 错误码治理初版；已同步可观测性协议 v1.2，仅展示已通过准入规则的 definition",
        "source": "事实源",
        "generated": "本文件由 `tools/observability/scripts/generate_error_code_docs.py` 生成，禁止手工维护码值事实。",
        "usage": "## 1. 使用说明",
        "registered": "当前登记 {definitions} 个 definition、{references} 个跨服务 reference。",
        "boundary": "未登记候选不等于可以继续使用；其处置边界见[仓内基线评审记录](../../../tools/observability/reviews/error-code-baseline-v1.2.md)。`0250`、`0330` 仍为 provisional，`1210` 为 reserved。",
        "modules": "## 2. 模块号段",
        "module_header": "| 号段 | 模块 | Steward | 状态 | 评审结论 |",
        "definitions": "## 3. 已登记错误定义",
        "definition_header": "| 错误码 | 格式 | 含义 | 名称 | 模块 | Owner | 分类 | HTTP | 级别 | 生命周期 | i18n 根键 | 引用服务 | 兼容说明 |",
        "unregistered": "## 4. 未登记边界",
        "unregistered_body": "以下内容不在本初版目录中：重复或跨服务冲突定义、Owner i18n 不完整定义、非 4xx/5xx 错误状态、未冻结号段，以及尚未证明精确对外值和消费者的 legacy 候选。已经发布链路证明的 `openjiuwen.121007` 作为 `legacy_other` 例外登记。\n\n其余候选必须先按基线评审记录完成处置，不得直接复制进 Manifest，也不得据此认定为可对外复用的错误码。",
        "none": "—",
    },
    "en_us": {
        "title": "# Studio 2.0 Error Code Catalog",
        "status": "Initial Studio 2.0 governance catalog, synchronized with observability protocol v1.2; only admitted definitions are shown",
        "source": "Source of truth",
        "generated": "This file is generated by `tools/observability/scripts/generate_error_code_docs.py`. Do not edit error-code facts manually.",
        "usage": "## 1. Usage",
        "registered": "The catalog currently registers {definitions} definitions and {references} cross-service references.",
        "boundary": "An omitted candidate is not automatically valid for continued use. See the [in-repository baseline review](../../../tools/observability/reviews/error-code-baseline-v1.2.md) for its disposition boundary. Modules `0250` and `0330` remain provisional; `1210` remains reserved.",
        "modules": "## 2. Module Ranges",
        "module_header": "| Range | Module | Steward | Status | Review conclusion |",
        "definitions": "## 3. Registered Definitions",
        "definition_header": "| Error code | Format | Meaning | Name | Module | Owner | Category | HTTP | Level | Lifecycle | i18n root | Referencing services | Compatibility |",
        "unregistered": "## 4. Unregistered Boundary",
        "unregistered_body": "This initial catalog excludes duplicate or cross-service conflicting definitions, definitions with incomplete owner i18n, non-4xx/5xx error statuses, non-frozen ranges, and legacy candidates without evidence of their exact public value and consumers. The verified published value `openjiuwen.121007` is registered as a `legacy_other` exception.\n\nResolve the remaining candidates through the baseline-review disposition before adding them to the Manifest. Omission from this catalog does not authorize public reuse.",
        "none": "—",
    },
}


def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    """Load the JSON-compatible YAML Manifest without third-party packages."""
    text = path.read_text(encoding="utf-8")
    payload = "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("#"))
    return json.loads(payload)


def render_catalog(manifest: dict[str, Any], locale: str) -> str:
    t = TEXT[locale]
    refs: dict[str, list[str]] = collections.defaultdict(list)
    for item in manifest["references"]:
        refs[item["full_code"]].append(item["service"])

    lines = [
        t["title"],
        "",
        f"> {t['status']}",
        ">",
        f"> {t['source']}：[`tools/observability/error-codes.yaml`](../../../tools/observability/error-codes.yaml)"
        if locale == "zh_cn"
        else f"> {t['source']}: [`tools/observability/error-codes.yaml`](../../../tools/observability/error-codes.yaml)",
        ">",
        f"> {t['generated']}",
        "",
        t["usage"],
        "",
        t["registered"].format(
            definitions=len(manifest["definitions"]), references=len(manifest["references"])
        ),
        "",
        t["boundary"],
        "",
        t["modules"],
        "",
        t["module_header"],
        "| --- | --- | --- | --- | --- |",
    ]
    note_key = "review_note_zh_cn" if locale == "zh_cn" else "review_note_en_us"
    for module in manifest["modules"]:
        lines.append(
            f"| `{module['module_code']}` | {module['module_name']} | {module['module_steward']} | "
            f"{module['allocation_status']} | {module[note_key]} |"
        )

    lines.extend(
        [
            "",
            t["definitions"],
            "",
            t["definition_header"],
            "| --- | --- | --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- | --- |",
        ]
    )
    summary_key = "summary_zh_cn" if locale == "zh_cn" else "summary_en_us"
    for item in manifest["definitions"]:
        reference_services = ", ".join(sorted(refs.get(item["full_code"], []))) or t["none"]
        summary = item[summary_key].replace("|", "\\|")
        compatibility = str(item.get("compatibility_note") or t["none"]).replace("|", "\\|")
        lines.append(
            f"| `{item['full_code']}` | {item['code_format']} | {summary} | `{item['name']}` | {item['owning_module']} | "
            f"{item['code_owner']} | {item['category']} | {item['http_status']} | "
            f"{item['default_level']} | {item['lifecycle_status']} | `{item['i18n_key']}` | "
            f"{reference_services} | {compatibility} |"
        )

    lines.extend(["", t["unregistered"], "", t["unregistered_body"], ""])
    return "\n".join(lines)


def expected_outputs(manifest: dict[str, Any]) -> dict[Path, str]:
    return {path: render_catalog(manifest, locale) for locale, path in OUTPUTS.items()}


def write_or_check(check: bool) -> int:
    manifest = load_manifest()
    stale = []
    for path, expected in expected_outputs(manifest).items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    print("error-code reference documents are up to date" if check else "generated error-code reference documents")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated documents differ")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
